name: Docker Image C:

on:
  push:
    branches: [microsoft]
  pull_request:
    branches: [microsoft]

jobs:

  build:

    runs-on: universal-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
